theme="dark_plus"

[editor]
true-color=true
line-number="relative"
rulers=[80]

[editor.smart-tab]
enable=false

[editor.lsp]
display-inlay-hints=true

[editor.inline-diagnostics]
cursor-line="hint"
other-lines="disable"

