[[language]]
name = "c"
file-types = ["c", "h"]
indent = {tab-width = 4, unit = "\t"}

[[language]]
name = "cpp"
file-types = ["cpp", "hpp"]
indent = {tab-width = 4, unit = "\t"}

[[language]]
name = "python"
file-types = ["py"]
indent = {tab-width = 4, unit = " "}
formatter = { command = "black" , args = ["-q", "-"] }
auto-format = true
